name: shoesly
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ##### C ######
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  ##### D ######
  dio: ^5.4.2+1
  ##### F ######
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_slidable: ^3.1.0
  ##### G ######
  get_it: ^7.6.8
  ##### I ######
  intl: ^0.19.0
  ##### J ######
  json_annotation: ^4.8.1
  ##### P ######
  pretty_dio_logger: ^1.3.1
  ##### R ######
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  syncfusion_flutter_sliders: ^25.2.4
  ##### U ######
  url_launcher: ^6.2.6
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  syncfusion_flutter_core: ^25.2.4
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_gen_runner:

flutter_gen:
  output: lib/core/utils/assets_managers

  integrations:
    flutter_svg: true
    lottie: true
    flare_flutter: false
    rive: false

  assets:
    outputs:
      class_name: AssetsManager

  fonts:
    enabled: false

  colors:
    enabled: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
